/**
 * SUPACLEAN price list — (name, category, base_price TSh, service_type).
 * Source: scripts/populate-items.sql / scripts/migrate-items-simple.sql.
 * Consumed by ensureItemsSchema.js at server startup.
 */
module.exports = [
  // Gents
  ['Suit 2 pcs', 'gents', 11000, 'Wash, Press & Hanged'],
  ['Suit 3 pcs', 'gents', 13000, 'Wash, Press & Hanged'],
  ['Coats', 'gents', 6000, 'Wash, Press & Hanged'],
  ['Velvet/Wool Coat', 'gents', 6000, 'Wash, Press & Hanged'],
  ['Sued Coat', 'gents', 5000, 'Wash, Press & Hanged'],
  ['Kaunda/Safari Suit', 'gents', 9000, 'Wash, Press & Hanged'],
  ['Pyjama suits', 'gents', 7000, 'Wash, Press & Hanged'],
  ['Trousers', 'gents', 4000, 'Wash, Press & Hanged'],
  ['Nigerian Suit Unstarched', 'gents', 9000, 'Wash, Press & Hanged'],
  ['Nigerian Suit Starched', 'gents', 11000, 'Wash, Press & Hanged'],
  ['Leather Jackets', 'gents', 15000, 'Wash, Press & Hanged'],
  ['Jackets', 'gents', 6000, 'Wash, Press & Hanged'],
  ['Spy Coats/Long Coat', 'gents', 7000, 'Wash, Press & Hanged'],
  ['Shorts', 'gents', 3000, 'Wash, Press & Hanged'],
  ['Shirts - Colored', 'gents', 2000, 'Wash, Press & Hanged'],
  ['Shirts - White', 'gents', 3000, 'Wash, Press & Hanged'],
  ['Pants/Boxers', 'gents', 3000, 'Wash, Press & Hanged'],
  ['Vests/Tie', 'gents', 1000, 'Wash, Press & Hanged'],
  ['Overall', 'gents', 6000, 'Wash, Press & Hanged'],
  ['Caps', 'gents', 2000, 'Wash, Press & Hanged'],
  ['Car Seat Covers', 'gents', 20000, 'Wash & Fold'],
  ['Curtains Standard', 'general', 5000, 'Wash, Press & Fold'],
  // Ladies
  ['Lady Suit 2 pcs', 'ladies', 8000, 'Wash, Press & Hanged'],
  ['Trouser/Skirt Suit 3pcs', 'ladies', 9000, 'Wash, Press & Hanged'],
  ['Kitenge Suit', 'ladies', 8000, 'Wash, Press & Hanged'],
  ['Lady Coat', 'ladies', 5000, 'Wash, Press & Hanged'],
  ['Long Skirt', 'ladies', 3500, 'Wash, Press & Hanged'],
  ['Custom Ceremonials', 'ladies', 10000, 'Wash, Press & Hanged'],
  ['Tshirts', 'ladies', 3000, 'Wash, Press & Hanged'],
  ['Night Dress', 'ladies', 3000, 'Wash, Press & Hanged'],
  ['Bath robe', 'ladies', 5000, 'Wash, Press & Hanged'],
  ['Brassier', 'ladies', 3500, 'Wash, Press & Hanged'],
  ['Blouse', 'ladies', 3500, 'Wash, Press & Hanged'],
  ['Sweater', 'ladies', 5000, 'Wash, Press & Hanged'],
  // General
  ['Towels - Face', 'general', 2000, 'Wash, Dry & Folded'],
  ['Towels - Hand', 'general', 4000, 'Wash, Dry & Folded'],
  ['Towels - Body', 'general', 6000, 'Wash, Dry & Folded'],
  ['Bed Covers King', 'general', 7000, 'Wash, Press & Fold'],
  ['Bed Covers Single', 'general', 5000, 'Wash, Press & Fold'],
  ['Bed Sheet Double', 'general', 4000, 'Wash, Press & Fold'],
  ['Bed Sheet Single', 'general', 3000, 'Wash, Press & Fold'],
  ['Duvet/Conforter Large', 'general', 10000, 'Wash & Fold'],
  ['Duvet/Conforter Medium', 'general', 8000, 'Wash & Fold'],
  ['Sleeping Bags', 'general', 8000, 'Wash & Fold'],
  ['Curtains Heavy', 'general', 6000, 'Wash, Press & Fold'],
  ['Curtains Light', 'general', 3000, 'Wash, Press & Fold'],
  ['Blankets', 'general', 9000, 'Wash & Fold'],
  ['Shoes', 'general', 3000, 'Dry Clean'],
  ['Carpets', 'general', 10000, 'Wash & Fold'],
  ['Wedding Dress standard', 'general', 25000, 'Wash, Press & Hanged'],
  ['Wedding Dress Large 4pc', 'general', 35000, 'Wash, Press & Hanged'],
  ['Kikoi', 'general', 4000, 'Wash, Press & Hanged'],
  ['Dollies', 'general', 5000, 'Washed Only'],
  ['Wash & Dry 1KG', 'general', 7000, 'Washed & Fold'],
  ['Wash Only 1KG', 'general', 3500, 'Washed & Fold'],
];
